spring:
  application:
    name: deployforge-worker
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          multiplier: 2
          max-retries: 3
        default-requeue-rejected: false
aws:
  s3:
    region: ${AWS_S3_REGION}
    bucket-name: ${AWS_S3_BUCKET_NAME}

